# Use an official Redis image as a parent image
FROM redis:latest

# Expose the default Redis port
EXPOSE 6379

# By default, Redis runs as the 'redis' user
USER redis

# Start the Redis server
CMD ["redis-server"]

